spring.application.name=oms

# Spring Kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# docker
#spring.docker.compose.profiles.active=myprofile

# kafka setup
oms.kafka.topics.command.name=order-command
oms.kafka.topics.command.number-of-partition=5
oms.kafka.topics.command.number-of-replica=1
oms.kafka.topics.event.name=order-event
oms.kafka.topics.event.number-of-partition=1
oms.kafka.topics.event.number-of-replica=1
oms.kafka.topics.proposal.name=order-proposal
oms.kafka.topics.proposal.number-of-partition=1
oms.kafka.topics.proposal.number-of-replica=1
oms.kafka.topics.account-info.name=account-info
oms.kafka.topics.account-info.number-of-partition=1
oms.kafka.topics.account-info.number-of-replica=1
oms.kafka.topics.persist.name=persistence
oms.kafka.topics.persist.number-of-partition=1
oms.kafka.topics.persist.number-of-replica=1
oms.kafka.group-id=oms

oms.kafka.symbol=SOLUSDT
oms.kafka.accounts.account0.account-key=account0
oms.kafka.accounts.account0.partition-id=0
# bybit only
oms.kafka.accounts.account0.category=linear
# bybit only
oms.kafka.accounts.account0.account-type=UNIFIED
oms.kafka.accounts.account0.name=bybit
oms.kafka.accounts.account1.account-key=account1
oms.kafka.accounts.account1.partition-id=1
oms.kafka.accounts.account1.category=linear
oms.kafka.accounts.account1.account-type=UNIFIED
oms.kafka.accounts.account1.name=bybit
#oms.kafka.accounts.account2.account-key=account2
#oms.kafka.accounts.account2.partition-id=2
#oms.kafka.accounts.account2.category=
#oms.kafka.accounts.account2.account-type=
#oms.kafka.accounts.account2.name=binance
#oms.kafka.accounts.account3.account-key=account3
#oms.kafka.accounts.account3.partition-id=3
#oms.kafka.accounts.account4.account-key=account4
#oms.kafka.accounts.account4.partition-id=4

# hazelcast
#spring.cache.type=HAZELCAST
#
#hazelcast.instance-name=trademaster-instance
#hazelcast.cluster-name=trademaster-cluster
#hazelcast.network.port.auto-increment=true
#hazelcast.network.port=5701 # Change port number as needed
#hazelcast.network.join.multicast.enabled=false
#hazelcast.network.join.tcp-ip.enabled=true
#hazelcast.network.join.tcp-ip.members=localhost